Portfolio Create and Rename Command Handlers
venusvavadiya/ticksbook-main pull request #16
Opened 2021-06-05 04:44 UTC by shailscript

2021-06-05 05:04 UTC, aditipatelpro approved these changes

2021-06-05 05:37 UTC, venusvavadiya requested changes

2021-06-05 05:37 UTC, venusvavadiya commented on libs/portfolio/domain/src/lib/command-handlers/create-portfolio.command-handler.spec.ts
> +      testPortfolioAggregateRepository,
Please use a fake repository.

2021-06-05 05:37 UTC, venusvavadiya commented on libs/portfolio/domain/src/lib/command-handlers/rename-portfolio.command-handler.spec.ts
> +      testPortfolioAggregateRepository,
Please use a fake repository.

2021-06-05 19:56 UTC, hashptl approved these changes

2021-06-05 22:56 UTC, hashptl submitted a review, later dismissed

2021-06-05 23:33 UTC, hashptl approved these changes

2021-06-05 23:37 UTC, venusvavadiya requested changes
We make the `save` blocking.

2021-06-05 23:37 UTC, venusvavadiya commented on libs/portfolio/domain/src/lib/command-handlers/rename-portfolio.command-handler.ts
> +    this.portfolioAggregateRepository.save(portfolioAggregate);
```suggestion
    await this.portfolioAggregateRepository.save(portfolioAggregate);
```

2021-06-05 23:37 UTC, venusvavadiya commented on libs/portfolio/domain/src/lib/command-handlers/create-portfolio.command-handler.ts
> +    this.portfolioAggregateRepository.save(portfolioAggregate);
```suggestion
    await this.portfolioAggregateRepository.save(portfolioAggregate);
```

2021-06-05 23:41 UTC, venusvavadiya approved these changes
Thanks for making the changes Shailendra! Looks good to me. Good work! 👏

2021-06-06 00:41 UTC, ronakmistry36 commented
@shailscript 
`__mocks__/portfolio-aggregate.repository.ts` - is there any reason for this separate file? looks like we are not using anywhere in this pull request

2021-06-06 00:53 UTC, ronakmistry36 commented on libs/portfolio/domain/src/lib/command-handlers/create-portfolio.command-handler.spec.ts
> +    jest.spyOn(testPortfolioAggregate, 'create');
``` 
jest.spyOn(testPortfolioAggregateRepository, 'save').mockResolvedValue(undefined);
jest.spyOn(testPortfolioAggregate, 'create');
```
do we need a convention over here for mocking void methods?

`PortfolioAggregatee - create() - returns void` 
`AggregateRepository - save() returns void`

2021-06-06 00:54 UTC, ronakmistry36 commented on libs/portfolio/domain/src/lib/command-handlers/create-portfolio.command-handler.spec.ts
> +    jest.spyOn(testPortfolioAggregate, 'create');
@venusvavadiya

2021-06-06 04:47 UTC, shailscript commented on libs/portfolio/domain/src/lib/command-handlers/create-portfolio.command-handler.spec.ts
> +    jest.spyOn(testPortfolioAggregate, 'create');
@ronakmistry36 I see, I think I had removed the `mockResolvedValue(undefined)` but maybe while I was doing multiple refactors it may have got unnoticed.

For the above comment, we are using the mocks. [Here](https://github.com/venusvavadiya/ticksbook-main/pull/16/files#diff-faecf2fe56dacb89fd05b9fad0023e55e64c8f8f8ba7fb1724f373858a91ed4dR7) is an example.

2021-06-06 05:05 UTC, ronakmistry36 commented on libs/portfolio/domain/src/lib/command-handlers/create-portfolio.command-handler.spec.ts
> +    jest.spyOn(testPortfolioAggregate, 'create');
For mock repository, What do you suggest about this rule which we have followed in previous project.
If - mock repository is used only once, we won't create a new file, but if its used at multiple locations then we will create a new file 

(Just trying to avoid premature abstraction) 

I am fine with this file if you are planning to use this repository in upcoming PRs.

2021-06-07 03:54 UTC, merged