Add ArchivePortfolioCommandHandler
venusvavadiya/ticksbook-main pull request #18
Opened 2021-06-07 14:48 UTC by shailscript

Partially resolves #20
Continues after #16

2021-06-07 22:33 UTC, venusvavadiya requested changes

2021-06-07 22:33 UTC, venusvavadiya commented on libs/portfolio/domain/src/lib/exception/portfolio-already-archived.exception.ts
> +export class PortfolioAlreadyArchivedException extends AggregateException {
Please rename the file and directory as `aggregate-exception`.
```suggestion
export class PortfolioAlreadyArchivedAggregateException extends AggregateException {
```

2021-06-07 22:33 UTC, venusvavadiya commented on libs/portfolio/domain/src/lib/exception/portfolio-not-archived.exception.ts
> +export class PortfolioNotArchivedException extends AggregateException {
```suggestion
export class PortfolioNotArchivedAggregateException extends AggregateException {
```

2021-06-07 22:33 UTC, venusvavadiya commented on libs/portfolio/domain/src/lib/command-handlers/archive-portfolio.command-handler.spec.ts
> +      testPortfolioAggregate.isArchived = false;
Do not test what `archive` does. Testing if it is called or not is sufficient. The responsibility of `archive` is already tested in the aggregate's spec file.

```suggestion
```

2021-06-07 22:33 UTC, venusvavadiya commented on libs/portfolio/domain/src/lib/command-handlers/archive-portfolio.command-handler.spec.ts
> +      expect(testPortfolioAggregate.isArchived).toBeTruthy();
```suggestion
```

2021-06-07 22:33 UTC, venusvavadiya commented on libs/portfolio/domain/src/lib/command-handlers/archive-portfolio.command-handler.spec.ts
> +    });
Business logic is already tested for the Aggregate. It is assumed that we are letting Exceptions bubble.

```suggestion
```

2021-06-07 22:38 UTC, shailscript commented on libs/portfolio/domain/src/lib/command-handlers/archive-portfolio.command-handler.spec.ts
> +      expect(testPortfolioAggregate.isArchived).toBeTruthy();
I was expecting this. Thanks!

2021-06-08 02:26 UTC, shailscript commented on libs/portfolio/domain/src/lib/command-handlers/archive-portfolio.command-handler.spec.ts
> +    });
Resolved in https://github.com/venusvavadiya/ticksbook-main/pull/18/commits/766759fe8436e29b646c76a3826a4da22113745a

2021-06-08 02:26 UTC, shailscript commented on libs/portfolio/domain/src/lib/command-handlers/archive-portfolio.command-handler.spec.ts
> +      expect(testPortfolioAggregate.isArchived).toBeTruthy();
Resolved in https://github.com/venusvavadiya/ticksbook-main/pull/18/commits/766759fe8436e29b646c76a3826a4da22113745a

2021-06-08 02:26 UTC, shailscript commented on libs/portfolio/domain/src/lib/command-handlers/archive-portfolio.command-handler.spec.ts
> +      testPortfolioAggregate.isArchived = false;
Resolved in https://github.com/venusvavadiya/ticksbook-main/pull/18/commits/766759fe8436e29b646c76a3826a4da22113745a

2021-06-08 02:26 UTC, shailscript commented on libs/portfolio/domain/src/lib/exception/portfolio-not-archived.exception.ts
> +export class PortfolioNotArchivedException extends AggregateException {
Resolved in https://github.com/venusvavadiya/ticksbook-main/pull/18/commits/edcba7bf84a94dfbfc5c31773c026132ceebe79c

2021-06-08 02:26 UTC, shailscript commented on libs/portfolio/domain/src/lib/exception/portfolio-already-archived.exception.ts
> +export class PortfolioAlreadyArchivedException extends AggregateException {
Resolved in https://github.com/venusvavadiya/ticksbook-main/pull/18/commits/edcba7bf84a94dfbfc5c31773c026132ceebe79c

2021-06-08 02:34 UTC, venusvavadiya approved these changes

2021-06-08 05:16 UTC, hashptl approved these changes

2021-06-09 18:19 UTC, aditipatelpro approved these changes

2021-06-09 20:10 UTC, ronakmistry36 approved these changes

2021-06-09 20:10 UTC, merged