OrderBookEntity and Friends
venusvavadiya/ticksbook-main pull request #26
Opened 2021-06-12 06:07 UTC by venusvavadiya

2021-06-12 09:31 UTC, hashptl submitted a review, later dismissed

2021-06-13 19:28 UTC, shailscript commented on libs/order-context/domain/src/lib/aggregate/order-book.aggregate.ts
> +  private applyOrderBookUnarchivedV1Event() {
That `d` would have been tough to catch! Good work 👍

2021-06-13 19:56 UTC, shailscript commented on libs/order-context/domain/src/lib/aggregate/order-book.aggregate.spec.ts
> +  describe('should apply OrderBookArchivedV1Event', () => {
Should we just bunch them together under `describe('applyEvent')`.
The line of thought here is that describe should build a context for the tests inside it. It is more like given this scope/precondition etc, we are expecting a few tests to behave as follows.

Open to discuss, because I think this could be a bit voluminous.

2021-06-13 20:05 UTC, shailscript requested changes
I have some questions and ideas on abstractions in test. Let's discuss those!

2021-06-13 21:48 UTC, venusvavadiya commented on libs/order-context/domain/src/lib/aggregate/order-book.aggregate.spec.ts
> +  describe('should apply OrderBookArchivedV1Event', () => {
Pushed

2021-06-13 21:49 UTC, venusvavadiya commented on libs/order-context/domain/src/lib/aggregate/order-book.aggregate.ts
> +  private applyOrderBookUnarchivedV1Event() {
I was surprised to be honest. Indeed!

2021-06-14 04:40 UTC, aditipatelpro approved these changes

2021-06-14 15:08 UTC, hashptl approved these changes

2021-06-14 18:20 UTC, shailscript approved these changes

2021-06-14 19:48 UTC, ronakmistry36 commented on libs/order-context/domain/src/lib/event-listener/order-book-aggregate.event-listener.spec.ts
> +      expect(testOrderBookEntity.isArchived).toStrictEqual(true);
Is there any reason for this -->  `expect(testOrderBookEntity.isArchived).toStrictEqual(true);` statement?

2021-06-14 19:48 UTC, ronakmistry36 commented on libs/order-context/domain/src/lib/event-listener/order-book-aggregate.event-listener.spec.ts
> +
`expect(testOrderBookEntity.isArchived).toStrictEqual(false);` - what do you think about placing this statement after line number `89`? 

if you follow the code execution, 
1. getById 
2. set isArchived = false 
3. save

2021-06-14 20:32 UTC, venusvavadiya commented on libs/order-context/domain/src/lib/event-listener/order-book-aggregate.event-listener.spec.ts
> +      expect(testOrderBookEntity.isArchived).toStrictEqual(true);
Nah! You are right. No reason. The above line sets the value so it is surely going to be true.

2021-06-14 21:06 UTC, ronakmistry36 approved these changes

2021-06-14 21:06 UTC, merged